resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/ruanbekker/concourse-test
    branch: master

jobs:
- name: hello-world-job
  public: true
  plan:
  - get: my-git-repo
  - task: task_print-hello-world
    config:
      platform: linux
      image_resource:
        source:
          repository: alpine
          tag: edge
      run:
        path: ./my-git-repo/ci/runme.sh
      