resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/matty86uk/concourse-test
    branch: master

- name: base
  type: docker-image
  source:
    repository: busybox
    tag: latest
   

jobs:
- name: hello-world-job
  public: true
  plan:
      - get: my-git-repo
      - get: base
      - task: print-hello
        image: base
        config:
          platform: linux      
          run:
            path: runme.sh
          