resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/matty86uk/concourse-test
    branch: master

- name: alpine
  type: docker-image
  source:
    repository: alpine
    tag: latest
   

jobs:
- name: hello-world-job
  public: true
  plan:
  - get: my-git-repo
  - get: alpine
  - task: print-hello
    image: alpine
    config:
      platform: linux      
      run:
        path: ci/runme.sh
      